version: "3.8"

services:
  api:
    # Pour prod avec image GHCR (recommandé)
    image: ghcr.io/${GH_OWNER:-louis-bouhours}/${GH_REPO:-ecrireback}:latest
    # Pour dev local, commente 'image' et décommente 'build'
    # build: .
    container_name: ecrireback
    depends_on:
      - mongo
      - redis
    env_file:
      - ./.env
    ports:
      # Expose l'API sur la machine hôte (change le port si besoin)
      - "8081:8081"
    networks:
      - ecrire-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PORT:-8081}/healthz >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: ecrire-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - ecrire-net
    # Pas d'exposition publique par défaut (sécurité)

  redis:
    image: redis:7-alpine
    container_name: ecrire-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - ecrire-net

networks:
  ecrire-net:
    driver: bridge

volumes:
  mongo-data:
  redis-data: