name: ecrireback
version: 1.0.0
description: API backend pour l'application de chat Ecrire

# Configuration de l'application
app:
  name: ecrireback
  port: 8080
  env: development

# Configuration de la base de données
database:
  mongodb:
    uri: mongodb://localhost:27017/ecriredb?authSource=admin
    name: EcrireDB
    
# Configuration Redis
redis:
  addr: localhost:6379
  password: ""
  db: 0

# Configuration de sécurité
security:
  jwt:
    secret: ${JWT_SECRET}
    expiry: 24h
  cors:
    allowed_origins:
      - http://localhost:3000
      - http://localhost:8080
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed_headers:
      - Origin
      - Content-Type
      - Accept
      - Authorization

# Configuration du serveur
server:
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s